# Generated by Django 6.0.4 on 2026-04-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('hotel', 'Hotel'), ('estate', 'Estate'), ('villa', 'Villa'), ('cottage', 'Cottage'), ('penthouse', 'Penthouse')], max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='property_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('not_available', 'Not Available')], max_length=50)),
                ('category', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent')], max_length=50)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
