# Generated by Django 6.0.4 on 2026-04-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
