# Generated by Django 6.0.4 on 2026-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurox', '0002_properties_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='virtual_tour_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
