# Generated by Django 6.0.4 on 2026-05-13 14:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurox', '0007_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='image1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image3'),
        ),
    ]
